### ISSUE TITLE
Modifications to rvtests pipeline

### ISSUE THREAD

**Issue by ngaddis** [RTIInternational/biocloud_gwas_workflows#8]
A few modifications are needed for the rvtests pipeline:
- [x] gzip output tsv files
- [x] add the ability to specify multiple rsq thresholds, as is done for maf
- [x] add option for ID conversion

**Comment by ngaddis** [comment]
@alexwaldrop Can you tackle this issue, or possibly enlist @jaamarks to help?

**Comment by alexwaldrop** [comment]
Yiss! I got it. @ngaddis are you wanting the ID conversion on the final tsv output? Where in the pipeline exactly?

**Comment by ngaddis** [comment]
As long as all the summary stats files have their IDs converted, it's up to you where you add the step
